package chat;

import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

public class ChatFrame extends javax.swing.JFrame implements ChatCallbackAdapter {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1580673677145725871L;
	private Chat chat;
         int vInt=0 ;

    /** Creates new form Chat */
    public ChatFrame() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        disableNewMessages();
        
        startChat();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessagesScrollPane = new javax.swing.JScrollPane();
        MessagesTextArea = new javax.swing.JTextArea();
        NewMessageScrollPane = new javax.swing.JScrollPane();
        NewMessageTextArea = new javax.swing.JTextArea();
        SendButton = new javax.swing.JButton();
        OnlineUsersLabel = new javax.swing.JLabel();
        OnlineUsers = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtPos = new javax.swing.JTextField();
        txtLoket = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat");

        MessagesTextArea.setEditable(false);
        MessagesTextArea.setColumns(20);
        MessagesTextArea.setRows(5);
        MessagesScrollPane.setViewportView(MessagesTextArea);

        NewMessageTextArea.setColumns(20);
        NewMessageTextArea.setRows(5);
        NewMessageScrollPane.setViewportView(NewMessageTextArea);

        SendButton.setText("Send");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        OnlineUsersLabel.setText("Online:");

        jButton1.setText("Panggil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Layani");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jButton3.setText("Count");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Client MSG");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("checkin");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("lewat");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtPos.setText("1");

        txtLoket.setText("loket01");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(OnlineUsersLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OnlineUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MessagesScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewMessageScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SendButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLoket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OnlineUsersLabel)
                    .addComponent(OnlineUsers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessagesScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewMessageScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        chat.sendMessage(NewMessageTextArea.getText());
        MessagesTextArea.append("Me: " + NewMessageTextArea.getText() + "\n");
        NewMessageTextArea.setText(null);
    }//GEN-LAST:event_SendButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      chat.sendPanggil(txtPos.getText(),txtLoket.getText()); 
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     // chat.sendPanggil("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       chat.sendQueue(String.valueOf( vInt++));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    chat.sendPanggilClient(NewMessageTextArea.getText(),"okeh");
     NewMessageTextArea.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       chat.sendcheck(NewMessageTextArea.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      chat.sendLewat(txtPos.getText(),txtLoket.getText()); 
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ChatFrame();
            }
        });
    }
    
    
    public void startChat() {
        MessagesTextArea.append("Connecting...");
        chat = new Chat(this);
        chat.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane MessagesScrollPane;
    private javax.swing.JTextArea MessagesTextArea;
    private javax.swing.JScrollPane NewMessageScrollPane;
    private javax.swing.JTextArea NewMessageTextArea;
    private javax.swing.JLabel OnlineUsers;
    private javax.swing.JLabel OnlineUsersLabel;
    private javax.swing.JButton SendButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtLoket;
    private javax.swing.JTextField txtPos;
    // End of variables declaration//GEN-END:variables

    public void disableNewMessages() {
        NewMessageTextArea.setEnabled(false);
        SendButton.setEnabled(false);
    }
    
    public void enableNewMessages() {
        NewMessageTextArea.setEnabled(true);
        SendButton.setEnabled(true);
    }
    
    @Override
    public void callback(JSONArray data) throws JSONException {}

    @Override
    public void on(String event, JSONObject obj) {
        try {
            switch (event) {
                case "user message":
                    MessagesTextArea.append(obj.getString("user") + ": " + obj.getString("message") + "\n");
                    break;
                    
                   case "panggil2":
                         
                      MessagesTextArea.append( obj.getString("loket") + "\n");
                    if ( obj.getString("panggil").equals("1")){
                    // JOptionPane.showMessageDialog(rootPane, obj.getString("user") );
                     jButton2.setEnabled(false);
                     jButton6.setEnabled(false);
                    }else{
                    jButton2.setEnabled(true);
                     jButton6.setEnabled(true);
                    }
                    break;
                case "broadcast_panggil":
                    //MessagesTextArea.append("PPPP : " + obj.getString("panggil") + "\n");
                     if ( obj.getString("antrian").equals("1")){
                    // JOptionPane.showMessageDialog(rootPane, obj.getString("user") );
                     jButton1.setEnabled(false);
                      jButton6.setEnabled(false);
                    }else{
                    jButton1.setEnabled(true);
                     jButton6.setEnabled(true);
                     }
                    break;
                    
                     case "whoareyou":
                    chat.sendcheck("089");
                    break;
                    
                    case "message_client":
                    MessagesTextArea.append("dari : " + obj.getString("panggil") + "\n");
                    // if ( obj.getString("panggil").equals("1")){
                    // JOptionPane.showMessageDialog(rootPane, obj.getString("user") );
                    // jButton2.setEnabled(false);
                    //}else{
                    //jButton2.setEnabled(true);
                    // }
                    break;
                    
                     case "q_satu":
                         jLabel1.setText(obj.getString("jml"));
                   // MessagesTextArea.append("PPPP : " + obj.getString("panggil") + "\n");
                    // if ( obj.getString("panggil").equals("1")){
                    // JOptionPane.showMessageDialog(rootPane, obj.getString("user") );
                    // jButton2.setEnabled(false);
                    //}else{
                    //jButton2.setEnabled(true);
                    // }
                    break;
                case "announcement":
                    MessagesTextArea.append(obj.getString("user") + " " + obj.getString("action") + "\n");
                    
                    MessagesTextArea.append(" ----------- ok ----------------- \n");
                    break;
                case "nicknames":
                    JSONArray names = obj.names();
                    String str = "";
                    for (int i=0; i < names.length(); i++) {
                        if (i != 0)
                            str += ", ";
                        str += names.getString(i);
                    }   OnlineUsers.setText(str);
                    break;
                default:
                    break;
            }
        } catch (JSONException ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public void onMessage(String message) {
    
       // JOptionPane.showMessageDialog(rootPane, message );
    }

    @Override
    public void onMessage(JSONObject json) {
    
        //   JOptionPane.showMessageDialog(rootPane, json );
    }

    @Override
    public void onConnect() {
        MessagesTextArea.append("done!\n");        
        enableNewMessages();
        
        String nickname = JOptionPane.showInputDialog(null, "Nickname", null, WIDTH);
        if (!nickname.isEmpty()) {
            chat.join(nickname);
            MessagesTextArea.append("You joined as " + nickname + "\n");
        }
    }

    @Override
    public void onDisconnect() {
        JOptionPane.showMessageDialog(null, "Connection lost", "Error", JOptionPane.ERROR_MESSAGE);
        disableNewMessages();
    }

    @Override
    public void onConnectFailure() {
        MessagesTextArea.append("error!\n");
    }

}